### ISSUE TITLE
Updating `wthome.{home,tale}dir_root` doesn't update the `root` of an assetstore.

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/wt_home_dirs#28]
### Step to reproduce

1. Deploy locally
2. Navigate to https://girder.local.wholetale.org/#plugins/wt_home_dir/config
3. Change root directories, click "Save".
4. Navigate to https://girder.local.wholetale.org/api/v1#!/assetstore/assetstore_find , click "Try it out!"

### Expected results
`root` in assetstore is updated

### Actual results
`root` is set to default/previous value.

**Comment by Xarthisius** [comment]
I noticed it updates after restart. Maybe that's safer, cause I don't know if webdav can handle it otherwise...

**Comment by hategan** [comment]
That's intentional (for performance and code simplicity reasons)
