### ISSUE TITLE
Implement Tale Workspaces

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/wt_home_dirs#4]
Web-dav mountable directory for each tale synched with girder in the same spirit as the home directories. This will also include a level of unit/integration testing similar to what is already done (girder + webdav server tests via circleCI).

Completion criteria:
* Implement changes to webdav server
* Update documentation
* Unit tests 
* Pull request
* Deployed to dev

**Comment by craig-willis** [comment]
No longer part of the v0.4 release.

**Comment by Xarthisius** [comment]
Done a while ago ;-)
