### ISSUE TITLE
Cannot remove homes wtassetstore even if it's empty

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/wt_home_dirs#5]
While trying to delete an existing, empty assetstore created by `wt_home_dirs`, I get:

```
$ curl -X DELETE --header 'Accept: application/json' --header 'Girder-Token: kC5hZworuCLEdvHQlGst89bVVytTpVJivGC3HyJ8ytoPedNRE0vUvNXN0ID79htW' 'http://localhost:8080/api/v1/assetstore/5ac52e355de5254ea623ebad'

Response code: 500

{
  "identifier": "girder.utility.assetstore.no-adapter",
  "message": "No AssetstoreAdapter for type: 100.",
  "type": "girder"
}
```

**Comment by hategan** [comment]
This, I cannot reproduce:

    curl -X DELETE --header 'Accept: application/json' --header 'Girder-Token: XpCfe0G7me4hlsAYpNw0YduxjScknUQ7ap7Uz4ourDo0HKFA0C9tYdru3CF5E1WN' 'http://localhost:8080/api/v1/assetstore/5aa4d5d3cbb11e19d886c5fe'
    {"message": "Deleted assetstore tales wtassetstore."}
    
wt_home_dirs listens for assetstore adapter query events (see `EventHandlers.AssetstoreQueryHandler`) and should handle them accordingly. It may be possible that there is some bad data left by previous dev code. I cannot unfortunately tell what's happening without more information.
